### PR TITLE
Check folder permission before listing content.

### PR DESCRIPTION
**Pull request by hdd**
Added check to see whether the folder we are trying to access has the rights to be read.
This stop riffle from throwing a OSError exception.

### CODE REVIEW

**Comment by martinpengellyphillips** [comment]
Cool, but doesn't appear to work on Windows:

```python
Traceback (most recent call last):
  File "C:\Users\Martin\data\identities\personal\project\riffle\source\riffle\model.py", line 487, in fetchMore
    additionalChildren = item.fetchChildren()
  File "C:\Users\Martin\data\identities\personal\project\riffle\source\riffle\model.py", line 119, in fetchChildren
    children = self._fetchChildren()
  File "C:\Users\Martin\data\identities\personal\project\riffle\source\riffle\model.py", line 201, in _fetchChildren
    for name in os.listdir(self.path):
WindowsError: [Error 5] Access is denied: u'C:\\$Recycle.Bin\\S-1-5-19\\*.*'
```

Might be better to ask forgiveness than permission here and just catch relevant exceptions.

That said, I wonder if this should be handled at all at this low level? Feels like it would be better to catch and handle higher up so that the information is not hidden and relevant UI can be displayed to the user.

**Comment by hdd** [comment]
Hi Martin, I've trying catching the exception from a higher level before attempting this, and didn't work either.  Kind of interesting that fails under win though, it seems it should be working as much as on *nix : https://docs.python.org/2/library/os.html
I'll have another look, thanks for looking into this.
Cheers.

**Comment by hdd** [comment]
Hi Martin, I've been changing approach , heading over a try except.
Please let me know if you want to have a logger or a qmessagebox in here so we can report the the issue to the user somehow.

**Comment by martinpengellyphillips** [comment]
Hey Lorenzo,

Yep that works on Windows now too. 

I guess we will definitely want to log a message for developers. For end users, a message box popup does seem pretty standard across other file browsers. My only concern is whether the *model* layer is the right place for that. However, I'm not too clear on where you could hook in to catch the errors in the Qt *view* layer. What do you think?

**Comment by hdd** [comment]
Same though...
Need to double check , but one option is to emit a custom exception and catching that up on the widget level, so we can decouple the two. Would that be good ?

**Comment by hdd** [comment]
Hi Martin I started looking on a solution for this notification, on a separate branch, but I first have to fight with the WindowsError exception which is not available un *nix..... back soon with a proper fix

**Comment by martinpengellyphillips** [comment]
Sounds good. I've been thinking about it more and whilst the model might handle the exception to guarantee model integrity, I think it would still re-raise it or as you say raise a new exception. Then it would be down to a new implementation (subclass) of the current view to handle that exception (message box, inline notification etc). 

Looking forward to seeing what you come up with!

**Comment by hdd** [comment]
Code updated. 
It's something which seems to be working.
Give it a go and let me know.

**Comment by martinpengellyphillips** [comment]
I've taken a look now. Definitely getting there :)

When I run the example, on Windows at least, the error dialog pops up twice - once initially and then immediately again after cancelling, so we should probably fix that. 

Also, it feels wrong to show the error and then navigate into the folder and show it empty. Perhaps we could abort the navigation into the folder on error (I believe OS file browsers generally do this).

As a variety of errors (other than just permission) could occur, I reckon it would make sense to generalise the error propagation and handling as well (`model.error` or something). What do you think?

**Comment by hdd** [comment]
Hey, yes, I noticed now that too.
I'll check where might be coming from and get it fixed.
Agreed in the empty folder, guess is better to bail off to the latest one visited before the error.
And yes handling a more generic error, seems  a sensible approach !

**Comment by hdd** [comment]
Hey , spent some good time today banging my head against this.
I think I got closer, but still the event gets somehow emitted twice, so for now I've been removing the messagebox as it was popping up twice, but the rest seems to be working.
Not sure how to prevent this double event, I'll keep having a look, but in the meanwhile see whether you like it more this way. (btw, though of doing it directly from the model, but there's some handy logic in the widget I didn't want to duplicate)

**Comment by martinpengellyphillips** [comment]
Ok, thanks! I was thinking of trying an alternate route of attack by subclassing the view instead, but I'll take a look at what you've done also.

**Comment by martinpengellyphillips** [comment]
Opened as [Issue 14](https://gitlab.com/4degrees/riffle/issues/14) on Gitlab where project has moved to. Happy to continue discussion either there or here.

**Comment by martinpengellyphillips** [comment]
FYI - making good progress on this now. Will hopefully have a final fix later this week.

**Comment by martinpengellyphillips** [comment]
See https://gitlab.com/4degrees/riffle/merge_requests/2

**Comment by hdd** [comment]
looking good.
Easier and cleaner.
Cheers.


2016-07-17 23:20 GMT+02:00 Martin Pengelly-Phillips <
notifications@github.com>:

**Comment by martinpengellyphillips** [comment]
Superseded by merged https://gitlab.com/4degrees/riffle/merge_requests/2

Thanks for the input!

**Pull request closed without merging**
